name: CI

on:
  push:
    branches: [main, update-home-page]
  pull_request:
    branches: [main, update-home-page]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Typecheck (tsc)
        run: npm run tsc

      - name: Run focused module-resolution test (jest)
        run: npm run test:module-resolution

  full-tests:
    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Typecheck (tsc)
        run: npm run tsc

      - name: Run full test suite (jest)
        run: npm run tests -- --ci --runInBand
